services:
  - type: web
    name: cyber-feed-backend
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    rootDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        value: placeholder_replace_me_in_render_ui
      - key: FRONTEND_URL
        value: placeholder_replace_me_in_render_ui
      - key: GEMINI_API_KEY
        value: placeholder_replace_me_in_render_ui
      - key: GROQ_API_KEY
        value: placeholder_replace_me_in_render_ui
